import 'package:flutter/material.dart';
import 'package:sqflite/sqflite.dart';
import 'databaseHelper.dart';
import 'product.dart';

class ProductForm extends StatefulWidget {
  const ProductForm({super.key});

  @override
  State<StatefulWidget> createState() {
    return ProductFormState();
  }
}

class ProductFormState extends State<ProductForm> {
  @override
  Widget build(BuildContext context) {
    final nameController = TextEditingController();
    final priceController = TextEditingController();
    final descriptionController = TextEditingController();
    final emailController = TextEditingController();

    return Scaffold(
      appBar: AppBar(
        title: const Text('Add Product'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(20),
        child: Column(
          children: [
            TextField(
              controller: nameController,
              decoration: const InputDecoration(labelText: 'Name Product'),
            ),
            TextField(
              controller: priceController,
              decoration: const InputDecoration(labelText: 'Price Product'),
              keyboardType: TextInputType.number,
            ),
            TextField(
              controller: descriptionController,
              decoration:
                  const InputDecoration(labelText: 'Description Product'),
            ),
            TextField(
              controller: emailController,
              decoration: const InputDecoration(labelText: 'Email Product'),
              keyboardType: TextInputType.emailAddress,
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () async {
                final product = Product(
                  id: DateTime.now()
                      .millisecondsSinceEpoch, // ID will be auto-generated by the database
                  name: nameController.text,
                  price: double.parse(priceController.text) ?? 0.0,
                  description: descriptionController.text,
                );
                DatabaseHelper().insertProduct(product);
                print('Producto ingreso en base de datos: ${product.name}');
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('Product added')),
                );
                Navigator.pop(context, true); // Close the form after saving
              },
              child: const Text('Save'),
            ),
          ],
        ),
      ),
    );
  }
}
